'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowRight, ChevronDown, Menu, X } from 'lucide-react'
import { navItems } from '@/lib/ironpulse-data'

export function SiteHeader() {
  const [open, setOpen] = useState(false)
  return <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-12"><Link href="/" className="font-display text-xl font-black tracking-[-0.04em]">IRON<span className="text-accent">PULSE</span></Link><nav className="hidden items-center gap-6 xl:flex" aria-label="Main navigation">{navItems.slice(0, 6).map(([label, href]) => <Link key={href} href={href} className="text-[11px] font-bold uppercase tracking-[0.13em] text-muted-foreground hover:text-foreground">{label}</Link>)}</nav><div className="flex items-center gap-4"><Link href="/sign-in" className="hidden text-[11px] font-bold uppercase tracking-[0.13em] text-muted-foreground hover:text-foreground sm:block">Sign in</Link><Link href="/free-trial" className="hidden bg-accent px-5 py-3 text-xs font-bold uppercase tracking-[0.15em] text-background transition-transform hover:-translate-y-0.5 sm:block">Start free trial</Link><button className="p-2 xl:hidden" aria-label={open ? 'Close menu' : 'Open menu'} onClick={() => setOpen(!open)}>{open ? <X size={22} /> : <Menu size={22} />}</button></div></div>{open && <nav className="border-t border-white/10 bg-background px-5 py-4 xl:hidden" aria-label="Mobile navigation">{navItems.map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)} className="block border-b border-white/10 py-4 text-sm font-bold uppercase tracking-[0.14em]">{label}</Link>)}<Link href="/sign-in" onClick={() => setOpen(false)} className="block border-b border-white/10 py-4 text-sm font-bold uppercase tracking-[0.14em]">Sign in</Link><Link href="/free-trial" onClick={() => setOpen(false)} className="mt-4 block bg-accent px-4 py-4 text-center text-xs font-bold uppercase tracking-[0.15em] text-background">Start free trial</Link></nav>}</header>
}

export function SiteFooter() { return <footer className="border-t border-white/10 bg-surface px-5 py-12 sm:px-8 lg:px-12"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-[1fr_2fr]"><div><Link href="/" className="font-display text-xl font-black tracking-[-0.04em]">IRON<span className="text-accent">PULSE</span></Link><p className="mt-4 max-w-xs text-sm leading-6 text-muted-foreground">Strength, conditioning, and community for the relentlessly curious.</p></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-3"><div className="space-y-3 text-xs font-bold uppercase tracking-[0.12em]"><p className="text-accent">Explore</p>{navItems.slice(0, 4).map(([label, href]) => <Link key={href} href={href} className="block text-muted-foreground hover:text-foreground">{label}</Link>)}</div><div className="space-y-3 text-xs font-bold uppercase tracking-[0.12em]"><p className="text-accent">Discover</p>{navItems.slice(4).map(([label, href]) => <Link key={href} href={href} className="block text-muted-foreground hover:text-foreground">{label}</Link>)}</div><div className="text-xs leading-6 text-muted-foreground"><p className="mb-3 font-bold uppercase tracking-[0.12em] text-accent">Visit</p>128 Franklin St<br />Brooklyn, NY 11222<br />Mon–Sun / 05:00–23:00</div></div></div><div className="mx-auto mt-14 flex max-w-7xl justify-between border-t border-white/10 pt-5 text-xs text-muted-foreground"><span>© 2026 IronPulse</span><span>Train with intention.</span></div></footer> }

export function PageShell({ children, eyebrow = 'IronPulse' }: { children: React.ReactNode; eyebrow?: string }) { return <><SiteHeader /><main className="min-h-screen overflow-hidden pt-20"><section className="border-b border-white/10 bg-surface px-5 py-20 sm:px-8 sm:py-28 lg:px-12"><div className="mx-auto max-w-7xl"><p className="eyebrow">{eyebrow}</p>{children}</div></section></main><SiteFooter /></> }

export function SectionHeading({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) { return <div><p className="eyebrow">{eyebrow}</p><h1 className="mt-5 max-w-4xl font-display text-5xl font-black uppercase leading-[0.9] tracking-[-0.06em] text-balance sm:text-7xl">{title}</h1>{copy && <p className="mt-7 max-w-xl text-base leading-7 text-muted-foreground">{copy}</p>}</div> }

export function ImageCard({ image, title, copy, href }: { image: string; title: string; copy?: string; href?: string }) { const content = <div className="group relative min-h-[320px] overflow-hidden"><img src={image} alt={title} className="absolute inset-0 h-full w-full object-cover grayscale transition duration-700 group-hover:scale-105 group-hover:grayscale-0" /><div className="absolute inset-0 bg-gradient-to-t from-background via-background/30 to-transparent" /><div className="relative flex h-full flex-col justify-end p-6"><h3 className="font-display text-3xl font-black uppercase tracking-[-0.05em]">{title}</h3>{copy && <p className="mt-2 max-w-sm text-sm leading-6 text-white/70">{copy}</p>}<span className="mt-5 flex size-9 items-center justify-center rounded-full border border-white/40"><ArrowRight size={15} /></span></div></div>; return href ? <Link href={href}>{content}</Link> : content }

export function FaqList({ items }: { items: [string, string][] }) { const [open, setOpen] = useState(0); return <div>{items.map(([question, answer], index) => <div key={question} className="border-t border-white/15"><button className="flex w-full items-center justify-between gap-5 py-6 text-left font-display text-lg font-bold uppercase tracking-[-0.02em]" onClick={() => setOpen(open === index ? -1 : index)} aria-expanded={open === index}>{question}<ChevronDown className={`shrink-0 transition-transform ${open === index ? 'rotate-180 text-accent' : ''}`} size={20} /></button>{open === index && <p className="max-w-2xl pb-6 text-sm leading-7 text-muted-foreground">{answer}</p>}</div>)}</div> }
