"use client"

import { useState } from "react"
import useSWR from "swr"
import { Card, Title, Badge } from "./member-portal"
const fetcher = (url: string) => fetch(url).then(async response => { if (!response.ok) throw new Error("load-failed"); return response.json() })
type Conversation = { id: string; trainerId: string; trainerName: string; lastMessageAt: string | null }
type Message = { id: string; senderUserId: string; body: string; createdAt: string }
export function MemberMessagesLive() { const [active, setActive] = useState<Conversation | null>(null); const [body, setBody] = useState(""); const { data: conversations, error, isLoading } = useSWR<Conversation[]>("/api/member/messages", fetcher); const { data: messages, mutate } = useSWR<Message[]>(active ? `/api/member/messages/${active.id}` : null, fetcher); const send = async () => { if (!active || !body.trim()) return; await fetch(`/api/member/messages/${active.id}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ body }) }); setBody(""); mutate() }; if (isLoading) return <><Title eyebrow="Direct support" title="Messages" /><div className="h-40 animate-pulse bg-card" /></>; if (error) return <Card className="p-8 text-sm text-muted-foreground">Couldn&apos;t load messages.</Card>; return <><Title eyebrow="Direct support" title="Messages" /><div className="grid gap-4 lg:grid-cols-[280px_1fr]"><Card className="divide-y divide-border">{conversations?.map(item => <button key={item.id} onClick={() => setActive(item)} className="block w-full p-4 text-left hover:bg-secondary"><Badge tone="muted">Trainer</Badge><p className="mt-2 font-bold">{item.trainerName}</p></button>)}{!conversations?.length && <p className="p-5 text-sm text-muted-foreground">No trainer conversations yet.</p>}</Card><Card className="flex min-h-[360px] flex-col p-5">{active ? <><h2 className="font-display text-xl font-black uppercase">{active.trainerName}</h2><div className="flex-1 space-y-3 py-6">{messages?.map(message => <p key={message.id} className="max-w-[80%] bg-secondary p-3 text-sm">{message.body}</p>)}</div><div className="flex gap-2"><input value={body} onChange={event => setBody(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && !event.nativeEvent.isComposing && event.keyCode !== 229) send() }} placeholder="Write a message" className="min-w-0 flex-1 border border-border bg-background p-3 text-sm"/><button onClick={send} className="bg-accent px-4 text-xs font-bold uppercase text-accent-foreground">Send</button></div></> : <p className="m-auto text-sm text-muted-foreground">Select a conversation.</p>}</Card></div></> }
