'use client'

import { useState } from 'react'
import useSWR, { mutate as globalMutate } from 'swr'
import { Bell, Check } from 'lucide-react'
import { Card, Badge, Title } from './member-portal'
const fetcher=(url:string)=>fetch(url).then(async response=>{if(!response.ok)throw new Error('load-failed');return response.json()})
const date=(value:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value))
export function MemberNotificationsLive(){const {data,error,isLoading,mutate}=useSWR('/api/member/account',fetcher,{revalidateOnFocus:false});const [busy,setBusy]=useState<string|null>(null);async function mark(notificationId:string){setBusy(notificationId);await fetch('/api/member/notifications',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({notificationId})});await Promise.all([mutate(),globalMutate('/api/member/overview')]);setBusy(null)}async function markAll(){setBusy('all');await fetch('/api/member/notifications',{method:'PUT'});await Promise.all([mutate(),globalMutate('/api/member/overview')]);setBusy(null)}if(isLoading)return <div className="animate-pulse space-y-5"><div className="h-10 w-64 bg-card"/><div className="h-72 bg-card"/></div>;if(error)return <Card className="p-8"><h1 className="font-display text-2xl font-black uppercase">Notifications unavailable.</h1><button onClick={()=>mutate()} className="mt-5 bg-accent px-5 py-3 text-xs font-bold uppercase tracking-[.14em] text-accent-foreground">Try again</button></Card>;const notifications=data?.data?.notifications??[];return <><Title eyebrow="Stay informed" title="Notifications" action={data?.data?.unreadCount?<button disabled={busy==='all'} onClick={markAll} className="text-xs font-bold uppercase tracking-[.14em] text-accent">Mark all read</button>:undefined}/><Card className="overflow-hidden p-0">{notifications.length?notifications.map((notification:{id:string;title:string;body:string;createdAt:string;read:boolean})=><div key={notification.id} className={`flex gap-4 border-b border-border p-5 last:border-0 ${notification.read?'opacity-60':''}`}><div className="grid size-10 shrink-0 place-items-center bg-secondary text-accent"><Bell size={17}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{notification.title}</h2>{!notification.read&&<Badge>New</Badge>}</div><p className="mt-1 text-sm leading-6 text-muted-foreground">{notification.body}</p><p className="mt-2 text-xs text-muted-foreground">{date(notification.createdAt)}</p></div>{!notification.read&&<button disabled={busy===notification.id} onClick={()=>mark(notification.id)} aria-label={`Mark ${notification.title} as read`} className="self-start text-muted-foreground hover:text-accent"><Check size={18}/></button>}</div>):<div className="p-8 text-sm text-muted-foreground">You&apos;re all caught up.</div>}</Card></>}
